  def test_lt(self) -> None:
        a = OrderedSet(self.a)
        self.assertFalse(a < self.a)
        a.discard(4)
        a.discard(15)
        a.discard(23)
        self.assertTrue(a < self.a)
        self.assertTrue(cast(OrderedSet[int], OrderedSet()) < self.a)
        b = OrderedSet(self.b)
        self.assertFalse(b < self.b)
        b.discard(3.1415926536)
        b.discard(1.4142135624)
        self.assertTrue(b < self.b)
        self.assertTrue(cast(OrderedSet[float], OrderedSet()) < self.b)
        c = OrderedSet(self.c)
        self.assertFalse(c < self.c)
        c.discard('Kili')
        c.discard('Fili')
        c.discard('Ori')
        c.discard('Dori')
        self.assertTrue(c < self.c)
        self.assertTrue(cast(OrderedSet[str], OrderedSet()) < self.c)
        d = OrderedSet(self.d)
        self.assertFalse(d < self.d)